name: Tests and linting
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  # Add test job when there are tests to be run
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: bandit
        run: make bandit
      - name: black
        run: make black
      - name: flake8
        run: make flake
      - name: isort
        run: make isort
